### ISSUE TITLE
Support for directly using youtube URLs 

### ISSUE THREAD

**Issue by fspoesis** [taizan-hokuto/pytchat#10]
A useful feature to have (especially within the CLI) would be to directly accept URLs and have the program automatically extract the ID necessary for parsing. An potential implementation could just be a simple regex like:

`((?<=(v|V)/)|(?<=be/)|(?<=(\?|\&)v=)|(?<=embed/))([\w-]+)`

Which should be enough to extract IDs from the majority of cases in my testing.

**Comment by taizan-hokuto** [comment]
Thanks for the request and giving regex example.
I'm going to implement this feature.

**Comment by taizan-hokuto** [comment]
Implemented in v0.1.1.
Available in CLI `--v` parameter and LiveChat, LiveChatAsync and Extrcator objects.

**Comment by fspoesis** [comment]
Thank you!
