### ISSUE TITLE
No comments after get

### ISSUE THREAD

**Issue by ArselMuginov** [taizan-hokuto/pytchat#24]
Tried to call chat.get().json() with live and archived, same result.

**Comment by taizan-hokuto** [comment]
Please write your environment (OS, python version), and the code you tried.

**Comment by ArselMuginov** [comment]
Should've done it in the first place, sorry.
Windows 10 2004, build 19041.630
Python 3.9.0
pip 20.3.1
pytchat from pip, 0.4.9

Archived
```python
>>> import pytchat
>>> chat = pytchat.create(video_id="KrknRtVdTUA")
>>> print(chat.get().json())
[]
```

Live
```python
>>> import pytchat
>>> chat = pytchat.create(video_id="5qap5aO4i9A")
>>> print(chat.get().json())
[]
```

**Comment by taizan-hokuto** [comment]
Sorry, I was unable to reproduce it in my environment (I was able to get JSON successfully).
It may be that we can or cannot get it due to network or regional circumstances.

**Comment by taizan-hokuto** [comment]
Fixed at v0.5.0. (

**Comment by koma-cute** [comment]
To provide more context, running the [example snippet from the wiki](https://github.com/taizan-hokuto/pytchat/wiki/Pytchatcore#example-code) results in the following response after patching https://github.com/taizan-hokuto/pytchat/blob/master/pytchat/parser/live.py#L32-L33 to return `jsn.get("error")`:

    pytchat.exceptions.ResponseContextError: {'code': 400, 'message': 'Request contains an invalid argument.', 'errors': [{'message': 'Request contains an invalid argument.', 'domain': 'global', 'reason': 'badRequest'}], 'status': 'INVALID_ARGUMENT'}

The value of `continuation` at runtime was `0ofMyAN1GhxDZzhLRFFvTGNXaDROalV0YUdwS1QzTWdBUT09KLrnsaia4-0CMAA4AEABShsIABAAGAAgADoAQABKAFCl4JiomuPtAlgDeABQ8dOap5rj7QJYq6yXp5fj7QJoAYIBAggBiAEAmgECCACgAdTxiaia4-0C`. The video ID used was `qhx65-hjJOs`.

**Comment by Sant268** [comment]
yes, Archived Streams aren't working, even by manual force_replay

`
import pytchat
chat = pytchat.create(video_id="live_string",force_replay = True)
while chat.is_replay():
    for c in chat.get().sync_items():
        print(c.json())
`

**Comment by taizan-hokuto** [comment]
Fixed at v0.5.1. Please try it.

**Comment by koma-cute** [comment]
Seems to be working for me.

**Comment by ArselMuginov** [comment]
Tried those in my message, both are working. Thanks!
