### ISSUE TITLE
question

### ISSUE THREAD

**Issue by NoodlesStamps** [taizan-hokuto/pytchat#25]
Thank you for updating again.
There seems to be no CLI functionality, is this temporary?
Or is it a permanent measure?
Thanks for maintain the awesome program

**Comment by taizan-hokuto** [comment]
Removed for technical reasons, but may be implemented if there is a solution.
I don't have much time to write on development.

**Comment by NoodlesStamps** [comment]
Thank you for replying to me in your busy schedule
looking forward to it
