### ISSUE TITLE
[feature] get archived chat data from continuation

### ISSUE THREAD

**Issue by miyuk** [taizan-hokuto/pytchat#31]
I use pytchat on FaaS like AWS Lambda.
However, there are not possible to create a program to get a long chat because the function's time is fixed.

If I use seektime parameter, can get continuous chat, but it has risk of  duplicate chat.

For that reason, I would like to improve it that by adding 'continuation' parameter.
Chat acquisition between functions can be obtained by passing the next continuation to the parameter.

I'd like to Pull Request with code like the one below, is that okay?

```python
print('\n######## First time ########')
chat = pytchat.create(video_id='uIx8l2xlYVY')
next_continuation = chat.continuation
chat.get() # get first comments
print(f'\n######## Second time ########')
chat = pytchat.create(video_id='uIx8l2xlYVY', replay_continuation=next_continuation )
chat.get() # get continuation comments
```

**Comment by taizan-hokuto** [comment]
Thank you for your PR.
