### ISSUE TITLE
chat.is_alive will stack with specific video

### ISSUE THREAD

**Issue by miyuk** [taizan-hokuto/pytchat#33]
bug
---

When I try to get an archive video that does not have the comments, I expect to occur an "NoContens Exception".

However, do specific video that does not have the comments, the program will get stuck because it try to get the chatdata eternally.

I don't found the detailed cause, so I will post only Issue. sorry.

appropriate video id(example): rCE2yhkPRr0
stacked video id(example): GDvXoHq8kGg

## reproduction code

```python
import pytchat
video_id = 'GDvXoHq8kGg'

chat = pytchat.create(video_id=video_id)

while chat.is_alive():
    chatdata = chat.get()
    print(chatdata.items)
        

try:
    chat.raise_for_status()
except pytchat.ChatDataFinished:
    print("chat data finished")
except Exception as e:
    print(type(e), str(e))

```

## output

```python
[]
[]
[]
...
# expected outpout
# <class 'pytchat.exceptions.NoContents'> Chat data stream is empty.
```

**Comment by taizan-hokuto** [comment]
Oddly enough, `GDvXoHq8kGg` returns the exact same chat data as the live feed.
In this case, pytchat cannot determine if it is live or archived, so it will fetch the chat forever.

Pytchat first tries to retrieve the live chat, and if that fails, it tries to retrieve the archived chat.

 `GDvXoHq8kGg` is the archived video and chats not available (on the page), but when try to fetch live chat, it succeed.
If you know that the target video is archived, use `force_replay=True`.

**Comment by miyuk** [comment]
thank you.
I understood.
