### ISSUE TITLE
Wrong indentation from line 171 - 181 in pytchat/pytchat/core/pytchat.py

### ISSUE THREAD

**Issue by icesukhatouch** [taizan-hokuto/pytchat#34]
![Screen Shot 2564-01-29 at 16 36 46](https://user-images.githubusercontent.com/29313423/106258414-5ea96e80-6250-11eb-9168-6cf40aa4dd1d.png)

Hi. I'm very new here.
Is it wrong indentation from line 171 - 181 in pytchat/pytchat/core/pytchat.py ??

**Comment by taizan-hokuto** [comment]
If  the count of `for loop` exceeds MAX_RETRY, then the process jumps to `else` clause (line:182), and raises exception that displays "Exceeded retry count.".

If not (=no error occurs in `try` clause and livechat_json is successfully retrieved BEFORE the count reaches MAX_RETRY), the process escapes from the `try` clause (`break`  line 177) and jumps to line 186.

This `for ... else...` behavior is unique to python as far as I know.
[https://docs.python.org/3/tutorial/controlflow.html#break-and-continue-statements-and-else-clauses-on-loops](https://docs.python.org/3/tutorial/controlflow.html#break-and-continue-statements-and-else-clauses-on-loops)

If you still have questions after going through the above explanation,  could you show me where is wrong and what code you think is correct?

**Comment by icesukhatouch** [comment]
Oh, you are right. I never knew this `for ... else... ` before. However, my code is working just update from 0.3.2 to 0.5.2.
Thank you.
