### ISSUE TITLE
Not Working?

### ISSUE THREAD

**Issue by LokCoder998** [taizan-hokuto/pytchat#35]
Hi

Did something change or is there a known problem? I am currently using this in a program, and even just the simple code that is on the wiki is not working. I've been using this for a while, but suddenly on friday it stopped working. (exchange "my chat id here" with the youtube chat id. 

For example
from pytchat import LiveChat
import time
chat = LiveChat(video_id = "my chat id here")

while chat.is_alive():
  try:
    data = chat.get()
    items = data.items
    for c in items:
      print(f"{c.datetime} [{c.author.name}]- {c.message}")
    time.sleep(3)
  except KeyboardInterrupt:
    chat.terminate()
    break

when i run this, it just finishes, and it doesnt actually pull anything.

**Comment by taizan-hokuto** [comment]
Could you please tell me the concrete video_id ?
Also, is your version of pytchat up to date?

In my current environment, it works just fine: e.g.
```
from pytchat import LiveChat
import time
chat = LiveChat(video_id = "eJ7ZkQ5TC08")

while chat.is_alive():
  try:
    data = chat.get()
    items = data.items
    for c in items:
        print(f"{c.datetime} [{c.author.name}]- {c.message}")
    time.sleep(3)
  except KeyboardInterrupt:
    chat.terminate()
    break
```

**Comment by LokCoder998** [comment]
> 
> 
> Could you please tell me the concrete video_id ?
> Also, is your version of pytchat up to date?
> 
> In my current environment, it works just fine: e.g.
> 
> ```
> from pytchat import LiveChat
> import time
> chat = LiveChat(video_id = "eJ7ZkQ5TC08")
> 
> while chat.is_alive():
>   try:
>     data = chat.get()
>     items = data.items
>     for c in items:
>         print(f"{c.datetime} [{c.author.name}]- {c.message}")
>     time.sleep(3)
>   except KeyboardInterrupt:
>     chat.terminate()
>     break
> ```

ah.. i apologize. i thought i set this to auto update... updating fixed the issue.

sorry about that.
