### ISSUE TITLE
Always receive "Chat data stream is empty"

### ISSUE THREAD

**Issue by tibfox** [taizan-hokuto/pytchat#39]
hey great work so far!
I tried to read the chat of an unlisted youtube stream chat and I always receive this message: 
Chat data stream is empty.

Also if I use a public available video id with chat messages in there (N-xNGZda6FY) I receive this error.
Can you please tell me what I am doing wrong or where my thinking process goes the wrong way? 

Thanks!

**Comment by tibfox** [comment]
dublicate of #37

**Comment by taizan-hokuto** [comment]
Fixed at v0.5.3.
Please upgrade pytchat by `pip install --upgrade pytchat`
