### ISSUE TITLE
Superchat Calculator seems to be inaccurate 

### ISSUE THREAD

**Issue by KaitoCross** [taizan-hokuto/pytchat#42]
When comparing the calculated money to the statistics from playboard.co, the Superchat Calculator's results are always less, by a significant amount.  
Comparison: Takanashi Kiara's O'riends 2nd concert - playboard.co says that on that day, she earned €2384 while the money from the SuperChat calculator adds up to around 1186€ after converting all currencies to €. That was her only stream on that day. The same happened with the TakaMori concert livestream, half of the money is missing.
I added a variable to count the total amount of superchats sent in a stream. The total amount of Superchats sent is always lower than what playboard.co suggests. The SuperChat calculator measures 94 Superchats, while she received 199 according to Playboard's data for that day. For the TakaMori concert it was 194 recorded by this software and 532 recorded by playboard.co     
All of this happens when I use it on livestream recordings using the asyncio example from the documentation

**Comment by taizan-hokuto** [comment]
Thank you for your report.
Since playboard.co seems to keep their aggregation program private, I don't think it can be argued that playboard.co is absolutely "accurate", but  I will try to verify whether there is a significant difference between the results obtained by YouTube API and pytchat.

**Comment by xenova** [comment]
The reason the value is inaccurate is because YouTube does not display all chat messages in the chat replay. For some reason, a lot of messages are hidden (probably to reduce server loads). The only accurate way - to my knowledge - to get all messages is to run the tool **while the stream is live**. YouTube should display all chat messages when it is happening live.

Hope this helps.

**Comment by KaitoCross** [comment]
> The reason the value is inaccurate is because YouTube does not display all chat messages in the chat replay. For some reason, a lot of messages are hidden (probably to reduce server loads). The only accurate way - to my knowledge - to get all messages is to run the tool **while the stream is live**. YouTube should display all chat messages when it is happening live.
> 
> Hope this helps.
Thank you.
I tested that and it's very true. Will have to code something to monitor livestreamers channels
