### ISSUE TITLE
Reuse httpx.Client

### ISSUE THREAD

**Issue by sgkoishi** [taizan-hokuto/pytchat#50]
Currently, multiple different clients are used:
For the first continuation:
https://github.com/taizan-hokuto/pytchat/blob/e865c25a4ec529c80e0ccdf442e04242915773e5/pytchat/core/pytchat.py#L98-L101
For each `get`:
https://github.com/taizan-hokuto/pytchat/blob/e865c25a4ec529c80e0ccdf442e04242915773e5/pytchat/core/pytchat.py#L103-L113
For `_get_livechat_json`, it creates a new client even though another one is given
https://github.com/taizan-hokuto/pytchat/blob/e865c25a4ec529c80e0ccdf442e04242915773e5/pytchat/core/pytchat.py#L166-L176

It would be nice to have all these clients combined and passed to the pytchat core. This may also help with member-only content.
```python
chat = pytchat.create(video_id="uIx8l2xlYVY", 
                      client=httpx.Client(http2=True, 
                                          headers=headers, 
                                          cookies=cookies, 
                                          proxies=proxies))
```

**Comment by taizan-hokuto** [comment]
Made it possible to reuse httpx.Client at new version: v0.5.5.
Please try it.

**Comment by sgkoishi** [comment]
Great thanks!
