### ISSUE TITLE
How do you compute the first continuation parameter?

### ISSUE THREAD

**Issue by tam-carre** [taizan-hokuto/pytchat#51]
I'm interested in scraping livechat in another language and I very intrigued by the `_build` function. I know there are other libs that compute it by scraping the page source, where it is present. You seem to have reverse-engineered how to generate it on your own. Could you explain how you figured out how to do that? Is it more robust than getting it from the page source, or does it just save a request?

**Comment by taizan-hokuto** [comment]
> how you figured out how to do that?

The first time I saw DevTools playing on YouTube, there was a parameter added to the url that seemed to be related to the chat, and I decided to analyze this parameter.

Currently, the payload related to the chat is POSTed, but at that time, the part related to the chat was GET as a parameter, as shown below:
````
https://www.youtube.com/live_chat/get_live_chat?continuation={parameter}&pbj=1"
````
I immediately noticed that the parameter was decoded in BASE64. In the binary obtained by decoding the parameters with BASE64, I found what looked like VideoID and ChannelID.
Using this as a clue, I tried to regenerate the parameters to get the chat.

The most difficult part was the chat time data.
There was a part of the chat URL parameter in the replay that changed according to the replay time. I thought that this might point to time data, but the relationship to the actual timestamp was not immediately clear.
After about two days of testing, I found out that the format is converted by run length every 7 bits.
(This is the [Varint of Protocol Buffers](https://developers.google.com/protocol-buffers/docs/encoding#structure) itself. But I didn't know anything about Protocol Buffers at that time.)

Then, I succeeded in generating a URL parameter to retrieve arbitrary chat data by stitching together a fixed raw binary with VideoID and time data as Varint.

Later, I found out about Protocol Buffers, and created a version that integrated the Protocol Buffers library.
The current version uses code that emulates only the part of Protocol Buffers' behavior that is necessary for payload generation.

**Comment by tam-carre** [comment]
Thank you very much for your detailed answer!!

Regarding getting data from another page to get the channel ID, you might be interested to know that [masterchat](https://github.com/holodata/masterchat/releases/tag/v0.9.0) provides an option for the user to supply both video ID and channel ID to skip loading the watch page.

**Comment by taizan-hokuto** [comment]
Thank you for your information.
