### ISSUE TITLE
Feature request: Custom emoji support

### ISSUE THREAD

**Issue by Xalaxis** [taizan-hokuto/pytchat#9]
It would be great if pytchat could download the custom emojis referenced in the log and then embed them in the HTML output at the appropriate place.

**Comment by taizan-hokuto** [comment]
Thank you for your wonderful idea.
New version 0.0.9 implements the ability to embed custom emoji in HTML files.
Please do not hesitate to let me know if there are any issues you have noticed or have any requests about it.

**Comment by Xalaxis** [comment]
Brilliant, thanks!
